# Generated by Django 6.0.1 on 2026-03-16 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180, verbose_name='Название источника')),
                ('sheet_url', models.URLField(help_text='Подходит обычная ссылка на Google-таблицу или прямая CSV-ссылка. Для первого этапа таблица должна быть доступна по ссылке.', verbose_name='Ссылка на Google Sheets или CSV')),
                ('worksheet_gid', models.CharField(blank=True, help_text='Если в ссылке уже есть gid, это поле можно не заполнять.', max_length=32, verbose_name='GID листа')),
                ('header_row', models.PositiveIntegerField(default=1, verbose_name='Строка с заголовками')),
                ('is_active', models.BooleanField(default=True, verbose_name='Источник активен')),
                ('auto_publish_imported', models.BooleanField(default=True, verbose_name='Сразу показывать импортированные акции на сайте')),
                ('archive_missing_on_import', models.BooleanField(default=False, verbose_name='Снимать с публикации пропавшие из таблицы акции')),
                ('last_imported_at', models.DateTimeField(blank=True, null=True, verbose_name='Последний успешный импорт')),
                ('last_import_error', models.TextField(blank=True, verbose_name='Последняя ошибка импорта')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Источник акций',
                'verbose_name_plural': 'Источники акций',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_row_key', models.CharField(blank=True, db_index=True, max_length=180, verbose_name='Ключ строки источника')),
                ('sync_with_source', models.BooleanField(default=True, help_text='Если выключить, импорт больше не будет перезаписывать эту акцию.', verbose_name='Обновлять при следующем импорте')),
                ('title', models.CharField(max_length=220, verbose_name='Название акции')),
                ('slug', models.SlugField(blank=True, max_length=240, unique=True, verbose_name='Внутренний адрес')),
                ('badge', models.CharField(blank=True, help_text='Например: Хит, 0-0-24, Trade-in, Cashback.', max_length=80, verbose_name='Короткая метка')),
                ('summary', models.TextField(blank=True, verbose_name='Краткое описание для списка')),
                ('details', models.TextField(blank=True, verbose_name='Подробные условия')),
                ('brand', models.CharField(blank=True, max_length=120, verbose_name='Бренд')),
                ('category', models.CharField(blank=True, max_length=120, verbose_name='Категория')),
                ('promo_code', models.CharField(blank=True, max_length=80, verbose_name='Промокод')),
                ('cta_label', models.CharField(blank=True, max_length=80, verbose_name='Текст кнопки')),
                ('cta_url', models.URLField(blank=True, verbose_name='Ссылка кнопки')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Дата начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок на странице')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Выделять как важную')),
                ('is_published', models.BooleanField(default=True, verbose_name='Показывать на сайте')),
                ('raw_data', models.JSONField(blank=True, default=dict, verbose_name='Исходные данные из таблицы')),
                ('imported_at', models.DateTimeField(blank=True, null=True, verbose_name='Когда импортировано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotions', to='promotions.promotionsource', verbose_name='Источник')),
            ],
            options={
                'verbose_name': 'Акция',
                'verbose_name_plural': 'Акции',
                'ordering': ['sort_order', '-is_featured', 'title'],
            },
        ),
    ]
