# Generated by Django 6.0.1 on 2026-03-16 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='promotion_kind',
            field=models.CharField(blank=True, choices=[('', 'Не указан'), ('promo_price', 'Промоцена / скидка / промо'), ('gift', 'Подарок'), ('preorder', 'Предзаказ')], max_length=24, verbose_name='Тип акции'),
        ),
        migrations.AddField(
            model_name='promotionsource',
            name='import_mode',
            field=models.CharField(choices=[('single_sheet', 'Один лист: каждая строка становится отдельной акцией'), ('last_worksheets', 'Последние листы книги: каждый лист становится отдельным предзаказом')], default='single_sheet', max_length=32, verbose_name='Как импортировать'),
        ),
        migrations.AddField(
            model_name='promotionsource',
            name='worksheets_to_import',
            field=models.PositiveIntegerField(default=1, help_text='Используется только для режима предзаказов из нескольких листов.', verbose_name='Сколько последних листов брать'),
        ),
    ]
