# Generated by Django 6.0.1 on 2026-03-19 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0002_promotion_promotion_kind_promotionsource_import_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='benefit_value',
            field=models.CharField(blank=True, help_text='Например: 380, 15% или Наушники в подарок.', max_length=120, verbose_name='Скидка / подарок'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='promotions/images/', verbose_name='Изображение акции'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='promo_price',
            field=models.CharField(blank=True, max_length=80, verbose_name='Промоцена'),
        ),
    ]
