# Generated by Django 6.0.1 on 2026-07-31 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0005_promotion_promotion_valid_date_range'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotionsource',
            name='archive_missing_on_import',
            field=models.BooleanField(default=True, help_text='Рекомендуется включить: если строку удалили из таблицы, связанная акция останется в админке, но исчезнет с сайта.', verbose_name='Снимать с публикации пропавшие из таблицы акции'),
        ),
    ]
