# Generated by Django 6.0.1 on 2026-07-31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("promotions", "0006_alter_promotionsource_archive_missing_on_import"),
    ]

    operations = [
        migrations.AddField(
            model_name="promotionsource",
            name="max_missing_percent",
            field=models.PositiveSmallIntegerField(
                default=50,
                help_text=(
                    "Если за один запуск пропадёт большая доля ранее импортированных акций, "
                    "синхронизация остановится до ручной проверки. Значение 100 отключает эту защиту."
                ),
                validators=[django.core.validators.MaxValueValidator(100)],
                verbose_name="Максимум пропавших акций за один импорт, %",
            ),
        ),
        migrations.AddField(
            model_name="promotionsource",
            name="minimum_expected_rows",
            field=models.PositiveIntegerField(
                default=1,
                help_text=(
                    "Импорт будет остановлен, если после проверки останется меньше акций. "
                    "Защищает от пустой или повреждённой выгрузки; укажите 0, если пустой источник допустим."
                ),
                verbose_name="Минимум распознанных акций",
            ),
        ),
        migrations.CreateModel(
            name="PromotionImportRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_dry_run",
                    models.BooleanField(
                        default=False,
                        verbose_name="Проверка без сохранения",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Выполняется"),
                            ("success", "Успешно"),
                            ("error", "Ошибка"),
                        ],
                        default="running",
                        max_length=16,
                        verbose_name="Статус",
                    ),
                ),
                ("created_count", models.PositiveIntegerField(default=0, verbose_name="Создано")),
                ("updated_count", models.PositiveIntegerField(default=0, verbose_name="Обновлено")),
                ("skipped_count", models.PositiveIntegerField(default=0, verbose_name="Пропущено")),
                (
                    "unpublished_count",
                    models.PositiveIntegerField(default=0, verbose_name="Снято с публикации"),
                ),
                ("duplicate_count", models.PositiveIntegerField(default=0, verbose_name="Дубликатов")),
                ("warnings", models.JSONField(blank=True, default=list, verbose_name="Предупреждения")),
                ("error", models.TextField(blank=True, verbose_name="Ошибка")),
                ("started_at", models.DateTimeField(auto_now_add=True, verbose_name="Запущено")),
                ("finished_at", models.DateTimeField(blank=True, null=True, verbose_name="Завершено")),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="import_runs",
                        to="promotions.promotionsource",
                        verbose_name="Источник",
                    ),
                ),
            ],
            options={
                "verbose_name": "Запуск импорта акций",
                "verbose_name_plural": "История импорта акций",
                "ordering": ["-started_at"],
                "indexes": [
                    models.Index(
                        fields=["source", "-started_at"],
                        name="promo_run_source_time",
                    )
                ],
            },
        ),
    ]
