# Generated by Django 6.0.1 on 2026-03-15 13:01

import datetime
import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True, verbose_name='Слаг')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Бренды',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', models.TextField(blank=True, default='Единая точка доступа к новостям компании, обучающим материалам, акциям и внутренним справочникам.', verbose_name='Вступление')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='KnowledgeArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True, verbose_name='Слаг')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Область знаний',
                'verbose_name_plural': 'Области знаний',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LearningIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', models.TextField(blank=True, default='Материалы по процессам компании, 1С, брендам, кредитным продуктам и товарным категориям.', verbose_name='Описание раздела')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='NewsIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', models.TextField(blank=True, default='Новости о новых моделях, внутренних изменениях, акциях и жизни компании.', verbose_name='Описание раздела')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True, verbose_name='Слаг')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Товарная категория',
                'verbose_name_plural': 'Товарные категории',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NewsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('summary', models.TextField(blank=True, max_length=300, verbose_name='Краткое описание')),
                ('category', models.CharField(choices=[('product', 'Новые модели'), ('corporate', 'Корпоративные новости'), ('promotion', 'Акции и спецпредложения'), ('instruction', 'Инструкции и обновления процессов')], default='corporate', max_length=30, verbose_name='Категория новости')),
                ('publish_date', models.DateField(default=datetime.date.today, verbose_name='Дата публикации')),
                ('body', wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('image', 2), ('video', 3), ('quote', 4), ('document', 5)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title'}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'bold', 'italic', 'link', 'ol', 'ul', 'hr', 'document-link', 'embed']}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 3: ('wagtail.embeds.blocks.EmbedBlock', (), {}), 4: ('wagtail.blocks.BlockQuoteBlock', (), {}), 5: ('wagtail.documents.blocks.DocumentChooserBlock', (), {})}, verbose_name='Содержимое')),
                ('brands', modelcluster.fields.ParentalManyToManyField(blank=True, to='portal.brand')),
                ('hero_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Главное изображение')),
                ('categories', modelcluster.fields.ParentalManyToManyField(blank=True, to='portal.productcategory')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='LearningMaterialPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('summary', models.TextField(blank=True, max_length=300, verbose_name='Краткое описание')),
                ('material_type', models.CharField(choices=[('process', 'Процесс'), ('product', 'Товар'), ('instruction', 'Инструкция'), ('promotion', 'Акция'), ('credit', 'Кредитный продукт'), ('reference', 'Справочник')], default='instruction', max_length=30, verbose_name='Тип материала')),
                ('body', wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('image', 2), ('video', 3), ('quote', 4), ('document', 5)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title'}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'bold', 'italic', 'link', 'ol', 'ul', 'hr', 'document-link', 'embed']}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 3: ('wagtail.embeds.blocks.EmbedBlock', (), {}), 4: ('wagtail.blocks.BlockQuoteBlock', (), {}), 5: ('wagtail.documents.blocks.DocumentChooserBlock', (), {})}, verbose_name='Содержимое')),
                ('areas', modelcluster.fields.ParentalManyToManyField(blank=True, to='portal.knowledgearea')),
                ('brands', modelcluster.fields.ParentalManyToManyField(blank=True, to='portal.brand')),
                ('hero_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Обложка')),
                ('categories', modelcluster.fields.ParentalManyToManyField(blank=True, to='portal.productcategory')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
