# Generated by Django 6.0.1 on 2026-03-15 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('news', '0002_news_is_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-created_at'], 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AddField(
            model_name='news',
            name='brands',
            field=models.ManyToManyField(blank=True, related_name='news_items', to='catalog.brand', verbose_name='Бренды'),
        ),
        migrations.AddField(
            model_name='news',
            name='category',
            field=models.CharField(choices=[('product', 'Новые модели'), ('corporate', 'Корпоративные новости'), ('promotion', 'Акции и спецпредложения'), ('instruction', 'Инструкции и обновления')], default='corporate', max_length=30, verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='news',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='news/covers/', verbose_name='Обложка'),
        ),
        migrations.AddField(
            model_name='news',
            name='product_categories',
            field=models.ManyToManyField(blank=True, related_name='news_items', to='catalog.productcategory', verbose_name='Категории товаров'),
        ),
        migrations.AddField(
            model_name='news',
            name='summary',
            field=models.TextField(blank=True, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='news',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=models.TextField(blank=True, verbose_name='Основной текст'),
        ),
        migrations.AlterField(
            model_name='news',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='news',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Заголовок'),
        ),
        migrations.CreateModel(
            name='NewsBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('block_type', models.CharField(choices=[('text', 'Текст'), ('image', 'Изображение'), ('video', 'Видео'), ('quote', 'Цитата'), ('file', 'Файл')], default='text', max_length=20, verbose_name='Тип блока')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Подзаголовок')),
                ('text', models.TextField(blank=True, verbose_name='Текст')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/blocks/images/', verbose_name='Изображение')),
                ('video_url', models.URLField(blank=True, verbose_name='Ссылка на видео')),
                ('document', models.FileField(blank=True, null=True, upload_to='news/blocks/files/', verbose_name='Файл')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Подпись')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='news.news', verbose_name='Новость')),
            ],
            options={
                'verbose_name': 'Блок новости',
                'verbose_name_plural': 'Блоки новости',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
