# Generated by Django 6.0.1 on 2026-03-16 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_brand_description_alter_brand_slug_and_more'),
        ('news', '0003_alter_news_options_news_brands_news_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='brands',
            field=models.ManyToManyField(blank=True, related_name='news_items', to='catalog.brand', verbose_name='Какие бренды связаны'),
        ),
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.CharField(choices=[('product', 'Новые модели'), ('corporate', 'Корпоративные новости'), ('promotion', 'Акции и спецпредложения'), ('instruction', 'Инструкции и обновления')], default='corporate', max_length=30, verbose_name='Тип новости'),
        ),
        migrations.AlterField(
            model_name='news',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='news/covers/', verbose_name='Главное изображение'),
        ),
        migrations.AlterField(
            model_name='news',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Когда создано'),
        ),
        migrations.AlterField(
            model_name='news',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Показывать на сайте'),
        ),
        migrations.AlterField(
            model_name='news',
            name='product_categories',
            field=models.ManyToManyField(blank=True, related_name='news_items', to='catalog.productcategory', verbose_name='Какие категории товаров связаны'),
        ),
        migrations.AlterField(
            model_name='news',
            name='summary',
            field=models.TextField(blank=True, verbose_name='Короткий анонс'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название новости'),
        ),
        migrations.AlterField(
            model_name='news',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Когда изменено'),
        ),
        migrations.AlterField(
            model_name='newsblock',
            name='block_type',
            field=models.CharField(choices=[('text', 'Текст'), ('image', 'Изображение'), ('video', 'Видео'), ('quote', 'Цитата'), ('file', 'Файл')], default='text', max_length=20, verbose_name='Что добавить'),
        ),
        migrations.AlterField(
            model_name='newsblock',
            name='caption',
            field=models.CharField(blank=True, max_length=255, verbose_name='Подпись или пояснение'),
        ),
        migrations.AlterField(
            model_name='newsblock',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок на странице'),
        ),
        migrations.AlterField(
            model_name='newsblock',
            name='title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Заголовок блока'),
        ),
    ]
