# Generated by Django 6.0.1 on 2026-03-16 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_featuretag'),
        ('news', '0004_alter_news_brands_alter_news_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='feature_tags',
            field=models.ManyToManyField(blank=True, related_name='news_items', to='catalog.featuretag', verbose_name='Какие фишки и метки показать'),
        ),
    ]
