# Generated by Django 6.0.1 on 2026-03-21 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_news_telegram_audience_news_telegram_target_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='telegram_include_group_chats',
            field=models.BooleanField(default=False, verbose_name='Также отправлять в группы Telegram'),
        ),
    ]
