# Generated by Django 6.0.1 on 2026-03-21 16:34

from django.db import migrations, models


def migrate_news_target_modes(apps, schema_editor):
    News = apps.get_model("news", "News")

    for item in News.objects.all():
        if item.telegram_audience == "groups":
            item.telegram_audience = "custom"
            item.save(update_fields=["telegram_audience"])
        elif item.telegram_audience == "all" and getattr(item, "telegram_include_group_chats", False):
            item.telegram_audience = "all_with_groups"
            item.save(update_fields=["telegram_audience"])


def reverse_news_target_modes(apps, schema_editor):
    News = apps.get_model("news", "News")

    for item in News.objects.all():
        if item.telegram_audience == "custom" and item.telegram_target_groups.exists():
            item.telegram_audience = "groups"
            item.save(update_fields=["telegram_audience"])
        elif item.telegram_audience == "all_with_groups":
            item.telegram_audience = "all"
            item.telegram_include_group_chats = True
            item.save(update_fields=["telegram_audience", "telegram_include_group_chats"])


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_news_telegram_target_chat_collections_and_more'),
        ('telegram_bot', '0005_telegrambroadcast_target_group_chats_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='telegram_target_group_chats',
            field=models.ManyToManyField(blank=True, related_name='group_news_items', to='telegram_bot.telegramsubscriber', verbose_name='Отдельные Telegram-группы'),
        ),
        migrations.AddField(
            model_name='news',
            name='telegram_target_subscribers',
            field=models.ManyToManyField(blank=True, related_name='direct_news_items', to='telegram_bot.telegramsubscriber', verbose_name='Отдельные получатели Telegram'),
        ),
        migrations.AlterField(
            model_name='news',
            name='telegram_audience',
            field=models.CharField(choices=[('all', 'Всем личным подписчикам'), ('all_with_groups', 'Всем личным подписчикам и всем Telegram-группам'), ('group_chats', 'Только Telegram-группам'), ('custom', 'Только выбранной аудитории')], default='all', max_length=20, verbose_name='Кому отправлять в Telegram'),
        ),
        migrations.AlterField(
            model_name='news',
            name='telegram_target_groups',
            field=models.ManyToManyField(blank=True, related_name='news_items', to='telegram_bot.telegramaudiencegroup', verbose_name='Группы личных подписчиков Telegram'),
        ),
        migrations.RunPython(migrate_news_target_modes, reverse_news_target_modes),
    ]
