# Generated by Django 6.0.1 on 2026-04-12 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('learning', '0010_learningblock_items_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220, verbose_name='Название теста')),
                ('slug', models.SlugField(blank=True, max_length=240, unique=True, verbose_name='Внутренний адрес')),
                ('summary', models.TextField(blank=True, verbose_name='Краткое описание')),
                ('intro', models.TextField(blank=True, help_text='Коротко объясни, чему поможет этот тест и на что обратить внимание.', verbose_name='Вступление перед стартом')),
                ('completion_message', models.TextField(blank=True, default='Пройди вопросы ещё раз, если хочешь лучше закрепить материал. Тест здесь нужен не для оценки, а для самопроверки.', verbose_name='Сообщение после прохождения')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок показа')),
                ('is_published', models.BooleanField(default=True, verbose_name='Показывать на сайте')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quizzes', to='learning.learningmaterial', verbose_name='Связанный обучающий материал')),
            ],
            options={
                'verbose_name': 'Тест для самопроверки',
                'verbose_name_plural': 'Тесты для самопроверки',
                'ordering': ['sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('prompt', models.TextField(verbose_name='Вопрос')),
                ('explanation', models.TextField(help_text='Это объяснение появится и при правильном, и при неправильном ответе.', verbose_name='Объяснение правильного варианта')),
                ('options_data', models.JSONField(blank=True, default=list, verbose_name='Варианты ответа')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quiz.quiz', verbose_name='Тест')),
            ],
            options={
                'verbose_name': 'Вопрос теста',
                'verbose_name_plural': 'Вопросы теста',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
