# Generated by Django 6.0.1 on 2026-03-18 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramBroadcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220, verbose_name='Заголовок уведомления')),
                ('message', models.TextField(verbose_name='Текст уведомления')),
                ('link_url', models.URLField(blank=True, verbose_name='Ссылка')),
                ('is_sent', models.BooleanField(default=False, verbose_name='Уже отправлено')),
                ('sent_count', models.PositiveIntegerField(default=0, verbose_name='Успешно отправлено')),
                ('failed_count', models.PositiveIntegerField(default=0, verbose_name='Не удалось отправить')),
                ('last_error', models.TextField(blank=True, verbose_name='Последняя ошибка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Отправлено')),
            ],
            options={
                'verbose_name': 'Уведомление в Telegram',
                'verbose_name_plural': 'Уведомления в Telegram',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TelegramSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(unique=True, verbose_name='Chat ID')),
                ('username', models.CharField(blank=True, max_length=255, verbose_name='Username')),
                ('first_name', models.CharField(blank=True, max_length=255, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=255, verbose_name='Фамилия')),
                ('language_code', models.CharField(blank=True, max_length=32, verbose_name='Язык')),
                ('is_active', models.BooleanField(default=True, verbose_name='Получает уведомления')),
                ('is_blocked', models.BooleanField(default=False, verbose_name='Бот заблокирован')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Подписался')),
                ('last_interaction_at', models.DateTimeField(auto_now=True, verbose_name='Последняя активность')),
            ],
            options={
                'verbose_name': 'Подписчик Telegram',
                'verbose_name_plural': 'Подписчики Telegram',
                'ordering': ['-last_interaction_at'],
            },
        ),
    ]
