# Generated by Django 6.0.1 on 2026-03-19 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramAudienceGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Название группы')),
                ('description', models.TextField(blank=True, verbose_name='Пояснение')),
            ],
            options={
                'verbose_name': 'Группа подписчиков Telegram',
                'verbose_name_plural': 'Группы подписчиков Telegram',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='telegrambroadcast',
            name='target_mode',
            field=models.CharField(choices=[('all', 'Всем подписчикам'), ('groups', 'Только выбранным группам')], default='all', max_length=20, verbose_name='Кому отправлять'),
        ),
        migrations.AddField(
            model_name='telegrambroadcast',
            name='target_groups',
            field=models.ManyToManyField(blank=True, related_name='broadcasts', to='telegram_bot.telegramaudiencegroup', verbose_name='Группы получателей'),
        ),
        migrations.AddField(
            model_name='telegramsubscriber',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='subscribers', to='telegram_bot.telegramaudiencegroup', verbose_name='Группы подписчиков'),
        ),
    ]
