# Generated by Django 6.0.1 on 2026-03-21 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0002_telegramaudiencegroup_telegrambroadcast_target_mode_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telegramsubscriber',
            options={'ordering': ['-last_interaction_at'], 'verbose_name': 'Получатель Telegram', 'verbose_name_plural': 'Получатели Telegram'},
        ),
        migrations.AddField(
            model_name='telegrambroadcast',
            name='include_group_chats',
            field=models.BooleanField(default=False, help_text='Сообщение уйдёт и в те группы, где есть бот и группа активирована командой.', verbose_name='Также отправить в группы Telegram'),
        ),
        migrations.AddField(
            model_name='telegramsubscriber',
            name='chat_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Название чата'),
        ),
        migrations.AddField(
            model_name='telegramsubscriber',
            name='chat_type',
            field=models.CharField(choices=[('private', 'Личный чат'), ('group', 'Группа'), ('supergroup', 'Супергруппа'), ('channel', 'Канал')], default='private', max_length=20, verbose_name='Тип чата'),
        ),
    ]
