# Generated by Django 6.0.1 on 2026-03-21 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0003_alter_telegramsubscriber_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegrambroadcast',
            name='target_mode',
            field=models.CharField(choices=[('all', 'Всем подписчикам'), ('groups', 'Только выбранным группам'), ('group_chats', 'Только Telegram-группам')], default='all', max_length=20, verbose_name='Кому отправлять'),
        ),
        migrations.CreateModel(
            name='TelegramChatCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Название объединения')),
                ('description', models.TextField(blank=True, verbose_name='Пояснение')),
                ('chats', models.ManyToManyField(blank=True, related_name='chat_collections', to='telegram_bot.telegramsubscriber', verbose_name='Telegram-группы')),
            ],
            options={
                'verbose_name': 'Объединение Telegram-групп',
                'verbose_name_plural': 'Объединения Telegram-групп',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='telegrambroadcast',
            name='target_chat_collections',
            field=models.ManyToManyField(blank=True, related_name='broadcasts', to='telegram_bot.telegramchatcollection', verbose_name='Объединения Telegram-групп'),
        ),
    ]
