# Generated by Django 6.0.1 on 2026-03-21 16:34

from django.db import migrations, models


def migrate_broadcast_target_modes(apps, schema_editor):
    TelegramBroadcast = apps.get_model("telegram_bot", "TelegramBroadcast")

    for broadcast in TelegramBroadcast.objects.all():
        if broadcast.target_mode == "groups":
            broadcast.target_mode = "custom"
            broadcast.save(update_fields=["target_mode"])
        elif broadcast.target_mode == "all" and getattr(broadcast, "include_group_chats", False):
            broadcast.target_mode = "all_with_groups"
            broadcast.save(update_fields=["target_mode"])


def reverse_broadcast_target_modes(apps, schema_editor):
    TelegramBroadcast = apps.get_model("telegram_bot", "TelegramBroadcast")

    for broadcast in TelegramBroadcast.objects.all():
        if broadcast.target_mode == "custom" and broadcast.target_groups.exists():
            broadcast.target_mode = "groups"
            broadcast.save(update_fields=["target_mode"])
        elif broadcast.target_mode == "all_with_groups":
            broadcast.target_mode = "all"
            broadcast.include_group_chats = True
            broadcast.save(update_fields=["target_mode", "include_group_chats"])


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0004_alter_telegrambroadcast_target_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegrambroadcast',
            name='target_group_chats',
            field=models.ManyToManyField(blank=True, related_name='broadcasts_as_group_recipient', to='telegram_bot.telegramsubscriber', verbose_name='Отдельные Telegram-группы'),
        ),
        migrations.AddField(
            model_name='telegrambroadcast',
            name='target_subscribers',
            field=models.ManyToManyField(blank=True, related_name='broadcasts_as_direct_recipient', to='telegram_bot.telegramsubscriber', verbose_name='Отдельные получатели Telegram'),
        ),
        migrations.AlterField(
            model_name='telegrambroadcast',
            name='target_groups',
            field=models.ManyToManyField(blank=True, related_name='broadcasts', to='telegram_bot.telegramaudiencegroup', verbose_name='Группы личных получателей'),
        ),
        migrations.AlterField(
            model_name='telegrambroadcast',
            name='target_mode',
            field=models.CharField(choices=[('all', 'Всем личным подписчикам'), ('all_with_groups', 'Всем личным подписчикам и всем Telegram-группам'), ('group_chats', 'Только Telegram-группам'), ('custom', 'Только выбранной аудитории')], default='all', max_length=20, verbose_name='Кому отправлять'),
        ),
        migrations.RunPython(migrate_broadcast_target_modes, reverse_broadcast_target_modes),
    ]
