# Generated by Django 6.0.1 on 2026-03-16 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='description',
            field=models.TextField(blank=True, verbose_name='Короткое пояснение'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='slug',
            field=models.SlugField(blank=True, max_length=140, unique=True, verbose_name='Внутренний адрес'),
        ),
        migrations.AlterField(
            model_name='knowledgearea',
            name='description',
            field=models.TextField(blank=True, verbose_name='Короткое пояснение'),
        ),
        migrations.AlterField(
            model_name='knowledgearea',
            name='slug',
            field=models.SlugField(blank=True, max_length=140, unique=True, verbose_name='Внутренний адрес'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='description',
            field=models.TextField(blank=True, verbose_name='Короткое пояснение'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=140, unique=True, verbose_name='Внутренний адрес'),
        ),
    ]
