# Generated by Django 6.0.1 on 2026-03-16 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_brand_description_alter_brand_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True, verbose_name='Внутренний адрес')),
                ('description', models.TextField(blank=True, verbose_name='Короткое пояснение')),
            ],
            options={
                'verbose_name': 'Фишка или метка',
                'verbose_name_plural': 'Фишки и метки',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
    ]
