# Generated by Django 6.0.1 on 2026-05-24 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_productcharacteristic_productcategorycharacteristic_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='featuretag',
            options={'ordering': ['name'], 'verbose_name': 'Фишка товара', 'verbose_name_plural': 'Фишки товаров'},
        ),
    ]
