# Generated by Django 6.0.1 on 2026-03-15 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220, verbose_name='Название')),
                ('summary', models.TextField(blank=True, verbose_name='Краткое описание')),
                ('content', models.TextField(blank=True, verbose_name='Основной текст')),
                ('material_type', models.CharField(choices=[('process', 'Процесс'), ('product', 'Товар'), ('instruction', 'Инструкция'), ('promotion', 'Акция'), ('credit', 'Кредитный продукт'), ('reference', 'Справочник')], default='instruction', max_length=30, verbose_name='Тип материала')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='learning/covers/', verbose_name='Обложка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('areas', models.ManyToManyField(blank=True, related_name='learning_materials', to='catalog.knowledgearea', verbose_name='Области знаний')),
                ('brands', models.ManyToManyField(blank=True, related_name='learning_materials', to='catalog.brand', verbose_name='Бренды')),
                ('categories', models.ManyToManyField(blank=True, related_name='learning_materials', to='catalog.productcategory', verbose_name='Категории товаров')),
            ],
            options={
                'verbose_name': 'Обучающий материал',
                'verbose_name_plural': 'Обучающие материалы',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='LearningBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('block_type', models.CharField(choices=[('text', 'Текст'), ('image', 'Изображение'), ('video', 'Видео'), ('quote', 'Цитата'), ('file', 'Файл')], default='text', max_length=20, verbose_name='Тип блока')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Подзаголовок')),
                ('text', models.TextField(blank=True, verbose_name='Текст')),
                ('image', models.ImageField(blank=True, null=True, upload_to='learning/blocks/images/', verbose_name='Изображение')),
                ('video_url', models.URLField(blank=True, verbose_name='Ссылка на видео')),
                ('document', models.FileField(blank=True, null=True, upload_to='learning/blocks/files/', verbose_name='Файл')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Подпись')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='learning.learningmaterial', verbose_name='Материал')),
            ],
            options={
                'verbose_name': 'Блок материала',
                'verbose_name_plural': 'Блоки материала',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
