# Generated by Django 6.0.1 on 2026-03-16 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_brand_description_alter_brand_slug_and_more'),
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='learningmaterial',
            options={'ordering': ['title'], 'verbose_name': 'Материал для обучения', 'verbose_name_plural': 'Материалы для обучения'},
        ),
        migrations.AlterField(
            model_name='learningblock',
            name='block_type',
            field=models.CharField(choices=[('text', 'Текст'), ('image', 'Изображение'), ('video', 'Видео'), ('quote', 'Цитата'), ('file', 'Файл')], default='text', max_length=20, verbose_name='Что добавить'),
        ),
        migrations.AlterField(
            model_name='learningblock',
            name='caption',
            field=models.CharField(blank=True, max_length=255, verbose_name='Подпись или пояснение'),
        ),
        migrations.AlterField(
            model_name='learningblock',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок на странице'),
        ),
        migrations.AlterField(
            model_name='learningblock',
            name='title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Заголовок блока'),
        ),
        migrations.AlterField(
            model_name='learningmaterial',
            name='areas',
            field=models.ManyToManyField(blank=True, related_name='learning_materials', to='catalog.knowledgearea', verbose_name='К каким темам относится'),
        ),
        migrations.AlterField(
            model_name='learningmaterial',
            name='brands',
            field=models.ManyToManyField(blank=True, related_name='learning_materials', to='catalog.brand', verbose_name='Какие бренды связаны'),
        ),
        migrations.AlterField(
            model_name='learningmaterial',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='learning_materials', to='catalog.productcategory', verbose_name='Какие категории товаров связаны'),
        ),
        migrations.AlterField(
            model_name='learningmaterial',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='learning/covers/', verbose_name='Главное изображение'),
        ),
        migrations.AlterField(
            model_name='learningmaterial',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Когда создано'),
        ),
        migrations.AlterField(
            model_name='learningmaterial',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Показывать на сайте'),
        ),
        migrations.AlterField(
            model_name='learningmaterial',
            name='summary',
            field=models.TextField(blank=True, verbose_name='Короткий анонс'),
        ),
        migrations.AlterField(
            model_name='learningmaterial',
            name='title',
            field=models.CharField(max_length=220, verbose_name='Название материала'),
        ),
        migrations.AlterField(
            model_name='learningmaterial',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Когда изменено'),
        ),
    ]
