# Generated by Django 6.0.1 on 2026-03-16 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_featuretag'),
        ('learning', '0002_alter_learningmaterial_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningmaterial',
            name='feature_tags',
            field=models.ManyToManyField(blank=True, related_name='learning_materials', to='catalog.featuretag', verbose_name='Какие фишки и метки показать'),
        ),
    ]
