# Generated by Django 6.0.1 on 2026-03-16 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_learningmaterial_feature_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningmaterial',
            name='product_full_description',
            field=models.TextField(blank=True, verbose_name='Полное описание товара'),
        ),
        migrations.AddField(
            model_name='learningmaterial',
            name='product_short_summary',
            field=models.TextField(blank=True, verbose_name='Краткое резюмирование'),
        ),
        migrations.AddField(
            model_name='learningmaterial',
            name='product_text_review',
            field=models.TextField(blank=True, verbose_name='Обзор текстом'),
        ),
        migrations.AddField(
            model_name='learningmaterial',
            name='product_video_review_url',
            field=models.URLField(blank=True, verbose_name='Ссылка на видеообзор YouTube'),
        ),
        migrations.AlterField(
            model_name='learningmaterial',
            name='content',
            field=models.TextField(blank=True, verbose_name='Общий текст материала'),
        ),
        migrations.AlterField(
            model_name='learningmaterial',
            name='summary',
            field=models.TextField(blank=True, verbose_name='Краткое описание для превью'),
        ),
        migrations.CreateModel(
            name='ProductDescriptionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('image', models.ImageField(upload_to='learning/product/description/', verbose_name='Изображение')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Подпись')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_description_images', to='learning.learningmaterial', verbose_name='Материал')),
            ],
            options={
                'verbose_name': 'Изображение для полного описания',
                'verbose_name_plural': 'Изображения для полного описания',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('title', models.CharField(max_length=220, verbose_name='Название фишки')),
                ('description', models.TextField(blank=True, verbose_name='Описание фишки')),
                ('client_pitch', models.TextField(blank=True, verbose_name='Как преподносить клиенту')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_features', to='learning.learningmaterial', verbose_name='Материал')),
            ],
            options={
                'verbose_name': 'Фишка товара',
                'verbose_name_plural': 'Фишки товара',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductReviewImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('image', models.ImageField(upload_to='learning/product/review/', verbose_name='Изображение')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Подпись')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_review_images', to='learning.learningmaterial', verbose_name='Материал')),
            ],
            options={
                'verbose_name': 'Изображение для текстового обзора',
                'verbose_name_plural': 'Изображения для текстового обзора',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductSalesScript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('title', models.CharField(max_length=220, verbose_name='Название скрипта')),
                ('script_text', models.TextField(verbose_name='Текст скрипта')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_sales_scripts', to='learning.learningmaterial', verbose_name='Материал')),
            ],
            options={
                'verbose_name': 'Скрипт продаж',
                'verbose_name_plural': 'Скрипты продаж',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('name', models.CharField(max_length=220, verbose_name='Название характеристики')),
                ('value', models.CharField(max_length=255, verbose_name='Значение')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_specifications', to='learning.learningmaterial', verbose_name='Материал')),
            ],
            options={
                'verbose_name': 'Характеристика товара',
                'verbose_name_plural': 'Характеристики товара',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
