# Generated by Django 6.0.1 on 2026-03-19 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_learningmaterial_product_full_description_and_more'),
        ('telegram_bot', '0002_telegramaudiencegroup_telegrambroadcast_target_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningmaterial',
            name='telegram_audience',
            field=models.CharField(choices=[('all', 'Всем подписчикам'), ('groups', 'Только выбранным группам')], default='all', max_length=20, verbose_name='Кому отправлять в Telegram'),
        ),
        migrations.AddField(
            model_name='learningmaterial',
            name='telegram_target_groups',
            field=models.ManyToManyField(blank=True, related_name='learning_materials', to='telegram_bot.telegramaudiencegroup', verbose_name='Группы подписчиков Telegram'),
        ),
    ]
