# Generated by Django 6.0.1 on 2026-03-21 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0007_learningmaterial_telegram_include_group_chats'),
        ('telegram_bot', '0004_alter_telegrambroadcast_target_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningmaterial',
            name='telegram_target_chat_collections',
            field=models.ManyToManyField(blank=True, related_name='learning_materials', to='telegram_bot.telegramchatcollection', verbose_name='Объединения Telegram-групп'),
        ),
        migrations.AlterField(
            model_name='learningmaterial',
            name='telegram_audience',
            field=models.CharField(choices=[('all', 'Всем подписчикам'), ('groups', 'Только выбранным группам'), ('group_chats', 'Только Telegram-группам')], default='all', max_length=20, verbose_name='Кому отправлять в Telegram'),
        ),
    ]
