# Generated by Django 6.0.1 on 2026-03-21 16:34

from django.db import migrations, models


def migrate_learning_target_modes(apps, schema_editor):
    LearningMaterial = apps.get_model("learning", "LearningMaterial")

    for material in LearningMaterial.objects.all():
        if material.telegram_audience == "groups":
            material.telegram_audience = "custom"
            material.save(update_fields=["telegram_audience"])
        elif material.telegram_audience == "all" and getattr(material, "telegram_include_group_chats", False):
            material.telegram_audience = "all_with_groups"
            material.save(update_fields=["telegram_audience"])


def reverse_learning_target_modes(apps, schema_editor):
    LearningMaterial = apps.get_model("learning", "LearningMaterial")

    for material in LearningMaterial.objects.all():
        if material.telegram_audience == "custom" and material.telegram_target_groups.exists():
            material.telegram_audience = "groups"
            material.save(update_fields=["telegram_audience"])
        elif material.telegram_audience == "all_with_groups":
            material.telegram_audience = "all"
            material.telegram_include_group_chats = True
            material.save(update_fields=["telegram_audience", "telegram_include_group_chats"])


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0008_learningmaterial_telegram_target_chat_collections_and_more'),
        ('telegram_bot', '0005_telegrambroadcast_target_group_chats_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningmaterial',
            name='telegram_target_group_chats',
            field=models.ManyToManyField(blank=True, related_name='group_learning_materials', to='telegram_bot.telegramsubscriber', verbose_name='Отдельные Telegram-группы'),
        ),
        migrations.AddField(
            model_name='learningmaterial',
            name='telegram_target_subscribers',
            field=models.ManyToManyField(blank=True, related_name='direct_learning_materials', to='telegram_bot.telegramsubscriber', verbose_name='Отдельные получатели Telegram'),
        ),
        migrations.AlterField(
            model_name='learningmaterial',
            name='telegram_audience',
            field=models.CharField(choices=[('all', 'Всем личным подписчикам'), ('all_with_groups', 'Всем личным подписчикам и всем Telegram-группам'), ('group_chats', 'Только Telegram-группам'), ('custom', 'Только выбранной аудитории')], default='all', max_length=20, verbose_name='Кому отправлять в Telegram'),
        ),
        migrations.AlterField(
            model_name='learningmaterial',
            name='telegram_target_groups',
            field=models.ManyToManyField(blank=True, related_name='learning_materials', to='telegram_bot.telegramaudiencegroup', verbose_name='Группы личных подписчиков Telegram'),
        ),
        migrations.RunPython(migrate_learning_target_modes, reverse_learning_target_modes),
    ]
