# Generated by Django 6.0.1 on 2026-04-07 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0009_learningmaterial_telegram_target_group_chats_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningblock',
            name='items_data',
            field=models.JSONField(blank=True, default=list, verbose_name='Внутренние элементы блока'),
        ),
        migrations.AlterField(
            model_name='learningblock',
            name='block_type',
            field=models.CharField(choices=[('text', 'Текст'), ('image', 'Изображение'), ('video', 'Видео'), ('quote', 'Цитата'), ('feature', 'Фишка'), ('sales_script', 'Скрипт продаж'), ('specification', 'Характеристика'), ('file', 'Файл')], default='text', max_length=20, verbose_name='Что добавить'),
        ),
        migrations.CreateModel(
            name='LearningBlockGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок в слайдере')),
                ('image', models.ImageField(upload_to='learning/blocks/gallery/', verbose_name='Изображение')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Подпись')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='learning.learningblock', verbose_name='Блок')),
            ],
            options={
                'verbose_name': 'Изображение блока',
                'verbose_name_plural': 'Изображения блока',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
