# Generated by Django 6.0.1 on 2026-05-20 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0010_learningblock_items_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningmaterial',
            name='comparison_overview',
            field=models.TextField(blank=True, help_text='Используется для материалов типа «Сравнение моделей».', verbose_name='Общее сравнение моделей'),
        ),
        migrations.AddField(
            model_name='learningmaterial',
            name='comparison_summary',
            field=models.TextField(blank=True, help_text='Короткий вывод: какую модель и в каком сценарии предлагать.', verbose_name='Итоговое резюмирование сравнения'),
        ),
        migrations.AlterField(
            model_name='learningmaterial',
            name='material_type',
            field=models.CharField(choices=[('process', 'Процесс'), ('product', 'Товар'), ('comparison', 'Сравнение моделей'), ('instruction', 'Инструкция'), ('promotion', 'Акция'), ('credit', 'Кредитный продукт'), ('reference', 'Справочник')], default='instruction', max_length=30, verbose_name='Тип материала'),
        ),
        migrations.CreateModel(
            name='LearningModelComparisonSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('name', models.CharField(max_length=220, verbose_name='Параметр')),
                ('values_data', models.JSONField(blank=True, default=dict, help_text='Ключ — название модели, значение — характеристика для этой модели.', verbose_name='Значения по моделям')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparison_specs', to='learning.learningmaterial', verbose_name='Материал')),
            ],
            options={
                'verbose_name': 'Строка сравнения моделей',
                'verbose_name_plural': 'Строки сравнения моделей',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LearningModelVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('name', models.CharField(max_length=220, verbose_name='Название модели')),
                ('short_summary', models.TextField(blank=True, verbose_name='Кратко о модели')),
                ('content', models.TextField(blank=True, verbose_name='Материал по модели')),
                ('image', models.ImageField(blank=True, null=True, upload_to='learning/model-variants/', verbose_name='Изображение модели')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_variants', to='learning.learningmaterial', verbose_name='Материал')),
            ],
            options={
                'verbose_name': 'Модель в сравнении',
                'verbose_name_plural': 'Модели в сравнении',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
