# Generated by Django 6.0.1 on 2026-05-20 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0011_learningmaterial_comparison_overview_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningblock',
            name='model_variant',
            field=models.ForeignKey(blank=True, help_text='Заполняй только для материалов типа «Сравнение моделей», если блок относится к конкретной модели.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='learning.learningmodelvariant', verbose_name='Модель сравнения'),
        ),
    ]
