# Generated by Django 6.0.1 on 2026-05-20 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0014_alter_learningblock_comparison_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningblock',
            name='comparison_section',
            field=models.CharField(blank=True, choices=[('general', 'Обычный блок страницы'), ('overview', 'Общее описание сравнения'), ('models', 'После карточек моделей'), ('summary', 'Итоговое резюмирование')], default='general', help_text='Для сравнения моделей выбери, где показать блок: в общем описании, после моделей, в итоговом резюме или внутри конкретной модели.', max_length=20, verbose_name='Раздел сравнения'),
        ),
    ]
