# Generated by Django 6.0.1 on 2026-05-20 14:26

from django.db import migrations, models


def move_comparison_materials_to_instruction(apps, schema_editor):
    LearningMaterial = apps.get_model("learning", "LearningMaterial")
    LearningMaterial.objects.filter(material_type="comparison").update(
        material_type="instruction"
    )


def restore_instruction_materials_as_comparison(apps, schema_editor):
    # The old comparison data is dropped in this migration, so the reverse
    # operation intentionally keeps material types unchanged.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0015_alter_learningblock_comparison_section'),
    ]

    operations = [
        migrations.RunPython(
            move_comparison_materials_to_instruction,
            restore_instruction_materials_as_comparison,
        ),
        migrations.RemoveField(
            model_name='learningmodelvariant',
            name='material',
        ),
        migrations.RemoveField(
            model_name='learningblock',
            name='model_variant',
        ),
        migrations.RemoveField(
            model_name='learningblock',
            name='comparison_section',
        ),
        migrations.RemoveField(
            model_name='learningmaterial',
            name='comparison_overview',
        ),
        migrations.RemoveField(
            model_name='learningmaterial',
            name='comparison_summary',
        ),
        migrations.AlterField(
            model_name='learningmaterial',
            name='material_type',
            field=models.CharField(choices=[('process', 'Процесс'), ('product', 'Товар'), ('instruction', 'Инструкция'), ('promotion', 'Акция'), ('credit', 'Кредитный продукт'), ('reference', 'Справочник')], default='instruction', max_length=30, verbose_name='Тип материала'),
        ),
        migrations.DeleteModel(
            name='LearningModelComparisonSpec',
        ),
        migrations.DeleteModel(
            name='LearningModelVariant',
        ),
    ]
