# Generated by Django 6.0.1 on 2026-05-20 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0016_remove_learningmodelvariant_material_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningblock',
            name='block_type',
            field=models.CharField(choices=[('text', 'Текст'), ('image', 'Изображение'), ('video', 'Видео'), ('quote', 'Цитата'), ('feature', 'Фишка'), ('sales_script', 'Скрипт продаж'), ('specification', 'Характеристика'), ('comparison_table', 'Сравнительная таблица'), ('file', 'Файл')], default='text', max_length=20, verbose_name='Что добавить'),
        ),
    ]
