# Generated by Django 6.0.1 on 2026-05-24 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0017_alter_learningblock_block_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='learningmaterial',
            options={'ordering': ['title'], 'verbose_name': 'Материал базы знаний', 'verbose_name_plural': 'База знаний'},
        ),
    ]
