# Generated by Django 6.0.1 on 2026-05-26 12:45

import django.db.models.deletion
import learning.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0018_admin_knowledge_base_labels'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresentationImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=220, verbose_name='Название материала')),
                ('presentation', models.FileField(help_text='После сохранения из текста слайдов будет создан материал базы знаний.', upload_to='learning/presentations/', validators=[learning.models.validate_presentation_file], verbose_name='Презентация .pptx')),
                ('publish_material', models.BooleanField(default=False, help_text='Если выключено, материал создастся скрытым и его можно будет проверить перед публикацией.', verbose_name='Сразу опубликовать материал')),
                ('import_report', models.TextField(blank=True, verbose_name='Отчёт импорта')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Загружено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('material', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presentation_import', to='learning.learningmaterial', verbose_name='Созданный материал')),
            ],
            options={
                'verbose_name': 'Импорт презентации',
                'verbose_name_plural': 'Импорт презентаций',
                'ordering': ['-created_at'],
            },
        ),
    ]
