# Generated by Django 6.0.1 on 2026-06-01 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0019_presentation_import'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningblock',
            name='block_type',
            field=models.CharField(choices=[('text', 'Текст'), ('image', 'Изображение'), ('video', 'Видео'), ('quote', 'Цитата'), ('feature', 'Фишка'), ('sales_script', 'Скрипт продаж'), ('specification', 'Характеристика'), ('table', 'Таблица'), ('comparison_table', 'Сравнительная таблица'), ('file', 'Файл')], default='text', max_length=20, verbose_name='Что добавить'),
        ),
    ]
